source 'https://rubygems.org'

gem 'rails', '3.2.3'
gem 'sqlite3'
gem 'cucumber'


# Gems used only for assets and not required
# in production environments by default.

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'uglifier', '>= 1.0.3'

  gem 'jquery-rails'

  gem 'watir-webdriver'
  gem 'webrat'
  gem 'json'
  gem 'sqlite3'
  gem 'haml'
  gem 'sinatra'
  gem 'data_mapper'
  gem 'gmaps4rails'
  gem 'nokogiri'
  gem 'mechanize'
  gem 'rest-client'
  end

